### ISSUE TITLE
Full-size images not downloading (only smaller thumbnails downloading)

### ISSUE THREAD

**Issue by aarongithu** [Naozumi520/discordImgCrawler#2]
I recall using this previously last year, and it worked as expected. However, I've tried using it again just now, having to reinstall it, and it's not downloading full-sized images... just thumbnails.

The downloaded files have long filenames like "001.jpg?ex=[BIGLONGNUMBER]&is=[BIGLONGNUMBER]&hm=[REALLYREALLYBIGLONGNUMBER]&=&width=433&height=350"

Deleting the extra text after ".jpg" in the filename results in an image, but -- as would seem obvious -- the image downloaded is limited by the "width=433&height=350" dimensions (or whatever the "width" and "height" are set at), rather than the larger image available by clicking through.

Do you know what's going wrong, or how to fix it?

Thanks!

**Comment by Naozumi520** [comment]
I think you just need to edit line 27 (main.js) to `const imageUrl = req.url().split(/\?format=|\?width=|\?ex=/g)[0];`, so it will result in like `001.jpg`, which will be the original image size.

**Comment by aarongithu** [comment]
That worked a treat! Thanks for your help.
